---
- name: Update Nginx Conf
  become: yes
  become_method: sudo
  block:
  - name: Move front file to nginx
    shell: mv /home/geoff/apps /var/www/

  - name: Move front file to nginx
    shell: mv /home/geoff/back /var/www/

  - name: Update nginx reverse proxy configuration
    ansible.builtin.template:
      src: nginx.j2
      dest: /etc/nginx/nginx.conf
      owner: geoff
      group: geoff
      mode: '0755'
      backup: yes
  - name: change right
    become: yes
    shell : chmod -R 777 /var/www/
  - name: Restart nginx service
    become: yes
    service: 
      name: nginx
      state: restarted
    notify: nginxServiceReStarted
