---
# handlers file for nginx
- name: "Ensure nginx service is started"
  become: yes
  service:
    name: nginx
    state: started
  listen: nginxServiceStarted

- name: "Restarted nginx service "
  become: yes
  service:
    name: nginx
    state: restarted
  listen: nginxServiceReStarted
